In [ ]:
import requests
import json
import pandas as pd

# Configuración de la API
API_BASE_URL = "https://carapi.app/api"
JWT_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXJhcGkuYXBwIiwic3ViIjoiOTU1YjYwNzQtMzBhYS00YjgyLWI2NmMtNzg5ODEzMjdiZjk2IiwiYXVkIjoiOTU1YjYwNzQtMzBhYS00YjgyLWI2NmMtNzg5ODEzMjdiZjk2IiwiZXhwIjoxNzQzOTg4NjgzLCJpYXQiOjE3NDMzODM4ODMsImp0aSI6ImJhOTBmMjFmLTk2MjktNDg2Ny04NGI3LTQxZTYzZjYxNmNhZCIsInVzZXIiOnsic3Vic2NyaXB0aW9ucyI6W10sInJhdGVfbGltaXRfdHlwZSI6ImhhcmQiLCJhZGRvbnMiOnsiYW50aXF1ZV92ZWhpY2xlcyI6ZmFsc2UsImRhdGFfZmVlZCI6ZmFsc2V9fX0.k5SrYOdBwun5-OT_rDnIRarTAlWDkxYt2ws9Pj9vIus"

# Encabezados de autenticación
headersInsanos = {
    "Authorization": f"Bearer {JWT_TOKEN}",
    "Accept": "application/json",
    "Content-Type": "application/json"
}

# Función para realizar la solicitud GET
def obtener_anios(tipo):
    url = f"{API_BASE_URL}{tipo}"
    response = requests.get(url, headers=headersInsanos)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error {response.status_code}: {response.text}")
        return []

# Obtener años de vehículos ligeros y motocicletas
anios_vehiculos_ligeros = obtener_anios("/years")

# Crear DataFrame con los resultados
df = pd.DataFrame({
    "Años Vehículos Ligeros": pd.Series(anios_vehiculos_ligeros, dtype=object),
})

df

   Años Vehículos Ligeros
0                    2026
1                    2025
2                    2024
3                    2023
4                    2022
5                    2021
6                    2020
7                    2019
8                    2018
9                    2017
10                   2016
11                   2015
12                   2014
13                   2013
14                   2012
15                   2011
16                   2010
17                   2009
18                   2008
19                   2007
20                   2006
21                   2005
22                   2004
23                   2003
24                   2002
25                   2001
26                   2000
27                   1999
28                   1998
29                   1997
30                   1996
31                   1995
32                   1994
33                   1993
34                   1992
35                   1991
36                   1990

In [4]:
# Función para obtener marcas (makes)
def obtener_makes():
    url = f"{API_BASE_URL}/makes"
    response = requests.get(url, headers=headersInsanos)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error {response.status_code}: {response.text}")
        return []

# Obtener marcas de vehículos
marcas = obtener_makes()

# Verificar la estructura de la respuesta para ver cómo se organizan los datos
# Mostramos los primeros elementos de la clave 'data' para verificar la estructura
if "data" in marcas:
    marcas_data = marcas["data"]  # Extrae las marcas de la clave 'data'
else:
    marcas_data = []

# Crear DataFrame con las marcas
df_makes = pd.DataFrame(marcas_data, columns=["id", "name"])

df_makes

    id          name
0    1         Acura
1   24    Alfa Romeo
2   64    AM General
3   44  Aston Martin
4    2          Audi
..  ..           ...
63  42         Tesla
64  22        Toyota
65  67       VinFast
66  43    Volkswagen
67  23         Volvo

[68 rows x 2 columns]

In [6]:
# Función para obtener modelos por año específico
def obtener_models_por_anio(anio):
    url = f"{API_BASE_URL}/models"
    params = {
        "year": anio  # Filtrar por un solo año
    }
    response = requests.get(url, headers=headersInsanos, params=params)
    if response.status_code == 200:
        return response.json()  # Devuelve los datos como un diccionario
    else:
        print(f"Error {response.status_code}: {response.text}")
        return {}

# Obtener modelos de vehículos entre 2015 y 2020
modelos_totales = []
for anio in range(2015, 2021):  # Del 2015 al 2020
    modelos_anio = obtener_models_por_anio(anio)
    if modelos_anio:
        modelos_totales.extend(modelos_anio.get("data", []))  # Agregar los modelos de ese año

# Filtrar modelos que no tienen la restricción de suscripción
modelos_filtrados = [modelo for modelo in modelos_totales if "subscription required" not in modelo["name"]]

# Crear DataFrame con los modelos disponibles
df_models = pd.DataFrame(modelos_filtrados, columns=["id", "name"])

df_models

      id       name
0    344       1500
1    140   2 Series
2    532        200
3    345       2500
4    286          3
..   ...        ...
595   78  Crosstrek
596   20        CT4
597   21        CT5
598  427        CT6
599  428      CT6-V

[600 rows x 2 columns]

In [8]:
# Función para obtener los motores por año específico
def obtener_engines_por_anio(anio):
    url = f"{API_BASE_URL}/engines"
    params = {
        "year": anio  # Filtrar por un solo año
    }
    print(f"Obteniendo datos para el año {anio}...")
    response = requests.get(url, headers=headersInsanos, params=params)

    # Imprimir la respuesta para ver si se están obteniendo datos
    print(f"Status code: {response.status_code}")
    print(f"Response text: {response.text[:200]}")  # Solo los primeros 200 caracteres

    if response.status_code == 200:
        return response.json()  # Devuelve los datos como un diccionario
    else:
        print(f"Error {response.status_code}: {response.text}")
        return {}

# Obtener motores de vehículos entre 2015 y 2020
engines_totales = []
for anio in range(2015, 2021):  # Del 2015 al 2020
    engines_anio = obtener_engines_por_anio(anio)
    if engines_anio:
        engines_totales.extend(engines_anio.get("data", []))  # Agregar los motores de ese año

# Si no se obtuvieron motores, imprime el error
if not engines_totales:
    print("No se obtuvieron motores en el rango de años especificado.")

# Crear DataFrame con los motores disponibles
df_engines = pd.DataFrame(engines_totales, columns=["id", "make_model_trim_id", "engine_type", "fuel_type", "cylinders", "size", "horsepower_hp", "horsepower_rpm", "torque_ft_lbs", "torque_rpm", "valves", "valve_timing", "cam_type", "drive_type", "transmission"])

# Mostrar el DataFrame
df_engines

Obteniendo datos para el año 2015...
Status code: 200
Response text: {"collection":{"url":"\/api\/engines?year=2015","count":100,"pages":29,"total":2878,"next":"\/api\/engines?year=2015\u0026page=2","prev":"","first":"\/api\/engines?year=2015","last":"\/api\/engines?ye
Obteniendo datos para el año 2016...
Status code: 200
Response text: {"collection":{"url":"\/api\/engines?year=2016","count":100,"pages":29,"total":2882,"next":"\/api\/engines?year=2016\u0026page=2","prev":"","first":"\/api\/engines?year=2016","last":"\/api\/engines?ye
Obteniendo datos para el año 2017...
Status code: 200
Response text: {"collection":{"url":"\/api\/engines?year=2017","count":100,"pages":30,"total":2975,"next":"\/api\/engines?year=2017\u0026page=2","prev":"","first":"\/api\/engines?year=2017","last":"\/api\/engines?ye
Obteniendo datos para el año 2018...
Status code: 200
Response text: {"collection":{"url":"\/api\/engines?year=2018","count":100,"pages":31,"total":3064,"next":"\/api\/engines?year=2018\u0026page=2","prev":"","first":"\/api\/engines?year=2018","last":"\/api\/engines?ye
Obteniendo datos para el año 2019...
Status code: 200
Response text: {"collection":{"url":"\/api\/engines?year=2019","count":100,"pages":30,"total":2992,"next":"\/api\/engines?year=2019\u0026page=2","prev":"","first":"\/api\/engines?year=2019","last":"\/api\/engines?ye
Obteniendo datos para el año 2020...
Status code: 200
Response text: {"collection":{"url":"\/api\/engines?year=2020","count":100,"pages":29,"total":2880,"next":"\/api\/engines?year=2020\u0026page=2","prev":"","first":"\/api\/engines?year=2020","last":"\/api\/engines?ye

,id,make_model_trim_id,engine_type,fuel_type,cylinders,size,horsepower_hp,horsepower_rpm,torque_ft_lbs,torque_rpm,valves,valve_timing,cam_type,drive_type,transmission
0,21078,21078,gas,premium unleaded (recommended),I4,2.0,150,6500.0,140.0,4300.0,16,Variable,Single overhead cam (SOHC),front wheel drive,5-speed shiftable automatic
1,21079,21079,gas,premium unleaded (recommended),I4,2.0,150,6500.0,140.0,4300.0,16,Variable,Single overhead cam (SOHC),front wheel drive,5-speed shiftable automatic
2,21080,21080,gas,premium unleaded (recommended),I4,2.4,201,7000.0,170.0,4400.0,16,Variable,Double overhead cam (DOHC),front wheel drive,6-speed manual
3,21081,21081,gas,premium unleaded (recommended),I4,2.0,150,6500.0,140.0,4300.0,16,Variable,Single overhead cam (SOHC),front wheel drive,5-speed shiftable automatic
4,21082,21082,gas,premium unleaded (recommended),V6,3.5,290,6200.0,267.0,4500.0,24,Variable,Single overhead cam (SOHC),front wheel drive,6-speed shiftable automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,6387,6387,mild hybrid,premium unleaded (required),I4,2.0,248,4300.0,273.0,1600.0,16,Variable,Double overhead cam (DOHC),all wheel drive,7-speed automated manual
596,6388,6388,mild hybrid,premium unleaded (required),I4,2.0,248,4300.0,273.0,1600.0,16,Variable,Double overhead cam (DOHC),all wheel drive,7-speed automated manual
597,6389,6389,mild hybrid,premium unleaded (required),I4,2.0,248,4300.0,273.0,1600.0,16,Variable,Double overhead cam (DOHC),all wheel drive,7-speed automated manual
598,6390,6390,mild hybrid,premium unleaded (required),V6,3.0,335,5000.0,369.0,1370.0,24,Variable,Double overhead cam (DOHC),all wheel drive,7-speed automated manual
599,6391,6391,mild hybrid,premium unleaded (required),V6,3.0,335,5000.0,369.0,1370.0,24,Variable,Double overhead cam (DOHC),all wheel drive,7-speed automated manual

In [9]:
# Función para obtener el millaje por año específico
def obtener_millas_por_anio(anio):
    url = f"{API_BASE_URL}/mileages"
    params = {
        "year": anio  # Filtrar por un solo año
    }
    print(f"Obteniendo datos para el año {anio}...")
    response = requests.get(url, headers=headersInsanos, params=params)

    # Imprimir la respuesta para ver si se están obteniendo datos
    print(f"Status code: {response.status_code}")
    print(f"Response text: {response.text[:200]}")  # Solo los primeros 200 caracteres

    if response.status_code == 200:
        return response.json()  # Devuelve los datos como un diccionario
    else:
        print(f"Error {response.status_code}: {response.text}")
        return {}

# Obtener motores de vehículos entre 2015 y 2020
millaje_totales = []
for anio in range(2015, 2021):  # Del 2015 al 2020
    millaje_anio = obtener_millas_por_anio(anio)
    if engines_anio:
        millaje_totales.extend(millaje_anio.get("data", []))  # Agregar los motores de ese año

# Si no se obtuvieron motores, imprime el error
if not millaje_totales:
    print("No se obtuvieron motores en el rango de años especificado.")

# Crear DataFrame con los motores disponibles
df_millaje = pd.DataFrame(millaje_totales, columns=["id", "make_model_trim_id", "fuel_tank_capacity", "combined_mpg", "epa_city_mpg", "epa_highway_mpg", "range_city", "range_highway", "battery_capacity_electric", "epa_time_to_charge_hr_240v_electric", "epa_kwh_100_mi_electric", "range_electric", "epa_highway_mpg_electric", "epa_city_mpg_electric", "epa_combined_mpg_electric"])

# Mostrar el DataFrame
print(df_millaje.head())

Obteniendo datos para el año 2015...
Status code: 200
Response text: {"collection":{"url":"\/api\/mileages?year=2015","count":100,"pages":29,"total":2878,"next":"\/api\/mileages?year=2015\u0026page=2","prev":"","first":"\/api\/mileages?year=2015","last":"\/api\/mileage
Obteniendo datos para el año 2016...
Status code: 200
Response text: {"collection":{"url":"\/api\/mileages?year=2016","count":100,"pages":29,"total":2882,"next":"\/api\/mileages?year=2016\u0026page=2","prev":"","first":"\/api\/mileages?year=2016","last":"\/api\/mileage
Obteniendo datos para el año 2017...
Status code: 200
Response text: {"collection":{"url":"\/api\/mileages?year=2017","count":100,"pages":30,"total":2975,"next":"\/api\/mileages?year=2017\u0026page=2","prev":"","first":"\/api\/mileages?year=2017","last":"\/api\/mileage
Obteniendo datos para el año 2018...
Status code: 200
Response text: {"collection":{"url":"\/api\/mileages?year=2018","count":100,"pages":31,"total":3064,"next":"\/api\/mileages?year=2018\u0026page=2","prev":"","first":"\/api\/mileages?year=2018","last":"\/api\/mileage
Obteniendo datos para el año 2019...
Status code: 200
Response text: {"collection":{"url":"\/api\/mileages?year=2019","count":100,"pages":30,"total":2992,"next":"\/api\/mileages?year=2019\u0026page=2","prev":"","first":"\/api\/mileages?year=2019","last":"\/api\/mileage
Obteniendo datos para el año 2020...
Status code: 200
Response text: {"collection":{"url":"\/api\/mileages?year=2020","count":100,"pages":29,"total":2880,"next":"\/api\/mileages?year=2020\u0026page=2","prev":"","first":"\/api\/mileages?year=2020","last":"\/api\/mileage
      id  make_model_trim_id fuel_tank_capacity  combined_mpg  epa_city_mpg  \
0  21078               21078               13.2          28.0          24.0
1  21079               21079               13.2          28.0          24.0
2  21080               21080               13.2          25.0          22.0
3  21081               21081               13.2          28.0          24.0
4  21082               21082               19.5          23.0          20.0

   epa_highway_mpg  range_city  range_highway battery_capacity_electric  \
0             35.0         317            462                      None
1             35.0         317            462                      None
2             31.0         290            409                      None
3             35.0         317            462                      None
4             28.0         390            546                      None

  epa_time_to_charge_hr_240v_electric  epa_kwh_100_mi_electric  \
0                                None                      NaN
1                                None                      NaN
2                                None                      NaN
3                                None                      NaN
4                                None                      NaN

   range_electric  epa_highway_mpg_electric  epa_city_mpg_electric  \
0             NaN                       NaN                    NaN
1             NaN                       NaN                    NaN
2             NaN                       NaN                    NaN
3             NaN                       NaN                    NaN
4             NaN                       NaN                    NaN

   epa_combined_mpg_electric
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN

In [10]:
def obtener_vehicles_attributes_por_anio(anio):
    atributos = [
        "bodies.type", "engines.cam_type", "engines.cylinders",
        "engines.drive_type", "engines.engine_type", "engines.fuel_type",
        "engines.transmission", "engines.valve_timing", "engines.valves"
    ]

    resultados = {}

    for atributo in atributos:
        url = f"{API_BASE_URL}/vehicle-attributes"
        params = {"attribute": atributo}

        response = requests.get(url, headers=headersInsanos, params=params)

        print(f"Consultando {atributo} para el año {anio} - Status: {response.status_code}")

        if response.status_code == 200:
            resultados[atributo] = response.json()  # Guarda los resultados por atributo
        else:
            print(f"Error en {atributo}: {response.text}")

    return resultados

# Obtener atributos de vehículos entre 2015 y 2020
vehicles_attributes_totales = []
for anio in range(2015, 2021):  # Del 2015 al 2020
    vehicles_attributes_anio = obtener_vehicles_attributes_por_anio(anio)
    if vehicles_attributes_anio:
        vehicles_attributes_totales.append({"year": anio, "attributes": vehicles_attributes_anio})

# Si no se obtuvieron datos, imprime el error
if not vehicles_attributes_totales:
    print("No se obtuvieron atributos de vehículos en el rango de años especificado.")

# Convertir datos en un DataFrame estructurado
vehicles_attributes_list = []
for entry in vehicles_attributes_totales:
    year = entry["year"]
    attributes = entry["attributes"]
    for attr, values in attributes.items():
        for value in values:
            vehicles_attributes_list.append({"year": year, "attribute": attr, "value": value})

# Crear DataFrame
columns = ["year", "attribute", "value"]
df_vehicles_attributes = pd.DataFrame(vehicles_attributes_list, columns=columns)

df_vehicles_attributes.loc[df_vehicles_attributes['attribute'] == 'bodies.type']

Consultando bodies.type para el año 2015 - Status: 200
Consultando engines.cam_type para el año 2015 - Status: 200
Consultando engines.cylinders para el año 2015 - Status: 200
Consultando engines.drive_type para el año 2015 - Status: 200
Consultando engines.engine_type para el año 2015 - Status: 200
Consultando engines.fuel_type para el año 2015 - Status: 200
Consultando engines.transmission para el año 2015 - Status: 200
Consultando engines.valve_timing para el año 2015 - Status: 200
Consultando engines.valves para el año 2015 - Status: 200
Consultando bodies.type para el año 2016 - Status: 200
Consultando engines.cam_type para el año 2016 - Status: 200
Consultando engines.cylinders para el año 2016 - Status: 200
Consultando engines.drive_type para el año 2016 - Status: 200
Consultando engines.engine_type para el año 2016 - Status: 200
Consultando engines.fuel_type para el año 2016 - Status: 200
Consultando engines.transmission para el año 2016 - Status: 200
Consultando engines.valve_timing para el año 2016 - Status: 200
Consultando engines.valves para el año 2016 - Status: 200
Consultando bodies.type para el año 2017 - Status: 200
Consultando engines.cam_type para el año 2017 - Status: 200
Consultando engines.cylinders para el año 2017 - Status: 200
Consultando engines.drive_type para el año 2017 - Status: 200
Consultando engines.engine_type para el año 2017 - Status: 200
Consultando engines.fuel_type para el año 2017 - Status: 200
Consultando engines.transmission para el año 2017 - Status: 200
Consultando engines.valve_timing para el año 2017 - Status: 200
Consultando engines.valves para el año 2017 - Status: 200
Consultando bodies.type para el año 2018 - Status: 200
Consultando engines.cam_type para el año 2018 - Status: 200
Consultando engines.cylinders para el año 2018 - Status: 200
Consultando engines.drive_type para el año 2018 - Status: 200
Consultando engines.engine_type para el año 2018 - Status: 200
Consultando engines.fuel_type para el año 2018 - Status: 200
Consultando engines.transmission para el año 2018 - Status: 200
Consultando engines.valve_timing para el año 2018 - Status: 200
Consultando engines.valves para el año 2018 - Status: 200
Consultando bodies.type para el año 2019 - Status: 200
Consultando engines.cam_type para el año 2019 - Status: 200
Consultando engines.cylinders para el año 2019 - Status: 200
Consultando engines.drive_type para el año 2019 - Status: 200
Consultando engines.engine_type para el año 2019 - Status: 200
Consultando engines.fuel_type para el año 2019 - Status: 200
Consultando engines.transmission para el año 2019 - Status: 200
Consultando engines.valve_timing para el año 2019 - Status: 200
Consultando engines.valves para el año 2019 - Status: 200
Consultando bodies.type para el año 2020 - Status: 200
Consultando engines.cam_type para el año 2020 - Status: 200
Consultando engines.cylinders para el año 2020 - Status: 200
Consultando engines.drive_type para el año 2020 - Status: 200
Consultando engines.engine_type para el año 2020 - Status: 200
Consultando engines.fuel_type para el año 2020 - Status: 200
Consultando engines.transmission para el año 2020 - Status: 200
Consultando engines.valve_timing para el año 2020 - Status: 200
Consultando engines.valves para el año 2020 - Status: 200

     year       attribute              value
0    2015     bodies.type          Cargo Van
1    2015     bodies.type        Convertible
2    2015     bodies.type              Coupe
3    2015     bodies.type  Ext Cargo Minivan
4    2015     bodies.type      Ext Cargo Van
..    ...             ...                ...
685  2020  engines.valves                 32
686  2020  engines.valves                 36
687  2020  engines.valves                 40
688  2020  engines.valves                 48
689  2020  engines.valves                 64

[690 rows x 3 columns]

In [12]:
df_vehicles_attributes.loc[df_vehicles_attributes['attribute'] == 'engines.valves']

     year       attribute value
103  2015  engines.valves     8
104  2015  engines.valves    12
105  2015  engines.valves    16
106  2015  engines.valves    18
107  2015  engines.valves    20
..    ...             ...   ...
685  2020  engines.valves    32
686  2020  engines.valves    36
687  2020  engines.valves    40
688  2020  engines.valves    48
689  2020  engines.valves    64

[72 rows x 3 columns]